services:
    _defaults:
       autowire: true
       autoconfigure: true

    zeaL\App\Core\HttpApplication:
        alias: application

    zeaL\App\Containers\ContainerModel:

    routeparser:
        class: FastRoute\RouteParser\Std

    datagenerator:
        class: FastRoute\DataGenerator\GroupCountBased

    FastRoute\RouteCollector:
        arguments:
            $routeParser: '@routeparser'
            $dataGenerator: '@datagenerator'



